#Chapter 05

##5.1 pandas 자료구조 소개

### 5.1.1 Series

In [3]:
from pandas import Series, DataFrame
import pandas as pd

In [70]:
obj = Series([4,7,-5,3])

In [71]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [72]:
obj.values

array([ 4,  7, -5,  3])

In [73]:
type(obj.values)

numpy.ndarray

In [8]:
obj.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [9]:
type(obj.index)

pandas.core.index.Int64Index

In [21]:
print obj[0], obj[1], obj[2], obj[3]

4 7 -5 3


In [23]:
print obj[[0, 1, 2, 3]]

0    4
1    7
2   -5
3    3
dtype: int64


In [36]:
obj2=Series([4,7,-5,3], index=['d','b','a','c'])

In [37]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [38]:
type(obj2.index)

pandas.core.index.Index

In [39]:
obj2['a']

-5

In [40]:
obj2['d'] = 6

In [51]:
print obj2[['d', 'b', 'a', 'c']]

d    6
b    7
a   -5
c    3
dtype: int64


In [42]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [43]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [44]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [45]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [46]:
'b' in obj2

True

In [47]:
'e' in obj2

False

In [48]:
sdata = {'Ohio':30555,'Texas':71000,'Oregon':16000,'Utah':5000}

In [49]:
obj3=Series(sdata)

In [50]:
obj3

Ohio      30555
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [52]:
states=['California','Ohio','Oregon','Texas']

In [53]:
obj4=Series(sdata,index=states)

In [54]:
obj4

California      NaN
Ohio          30555
Oregon        16000
Texas         71000
dtype: float64

In [55]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [56]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [57]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [58]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [62]:
obj3

Ohio      30555
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [63]:
obj4

California      NaN
Ohio          30555
Oregon        16000
Texas         71000
dtype: float64

In [64]:
obj3+obj4

California       NaN
Ohio           61110
Oregon         32000
Texas         142000
Utah             NaN
dtype: float64

In [34]:
obj4.name = 'population'

In [35]:
obj4.index.name = 'state'

In [74]:
obj4

California      NaN
Ohio          30555
Oregon        16000
Texas         71000
dtype: float64

In [75]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [76]:
obj.index=['Bob', 'Steve', 'Jeff', 'Ryan']

In [77]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 5.1.2 DataFrame

In [78]:
data={
    'state': ['Ohio','Ohio','Ohio','Nevada','Nevada'],
    'year': [2000,2001,2002,2001,2002],
    'pop': [1.5,1.7,3.6,2.4,2.9]
}

In [79]:
frame=DataFrame(data)

In [80]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [81]:
DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [82]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [83]:
frame2 = DataFrame(data, columns=['year','state','pop','debt'], index=['one','two','three','four','five'])

In [84]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [85]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

- DataFrame의 각 컬럼은 Series로서 다루어질 수 있다.

In [46]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [47]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [48]:
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [49]:
frame2['debt'] = 16.5

In [50]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [86]:
frame2['debt'] = np.arange(5.)

In [87]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [88]:
val = Series([-1.2,-1.5,-1.7], index=['two','four','five'])

In [89]:
frame2['debt'] = val

In [55]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [56]:
frame2['eastern'] = frame2.state == 'Ohio'

In [57]:
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

In [58]:
del frame2['eastern']

In [59]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [90]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [94]:
pop = {
    'Nevada': {2001: 2.4, 2002: 2.9},
    'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}
}

In [95]:
frame3=DataFrame(pop)

In [96]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [97]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [98]:
DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [102]:
pdata={
    'Ohio': frame3['Ohio'][0:2],
    'Nevada': frame3['Nevada'][:2]
}

In [103]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [104]:
frame3.index.name = 'year';
frame3.columns.name = 'state';

In [105]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [107]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [108]:
type(frame3.values)

numpy.ndarray

In [70]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

### 5.1.3 색인 객체 

In [109]:
obj = Series(range(3), index=['a','b','c'])

In [110]:
obj

a    0
b    1
c    2
dtype: int64

In [111]:
index=obj.index

In [112]:
index

Index([u'a', u'b', u'c'], dtype='object')

In [113]:
index[1:]

Index([u'b', u'c'], dtype='object')

- Index 객체는 immutable 이다.

In [115]:
index[1] = 'd'

TypeError: Indexes does not support mutable operations

In [76]:
index = pd.Index(np.arange(3))

In [77]:
obj2=Series([1.5,-2.5,0],index=index)

In [78]:
obj2.index is index

True

In [79]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [80]:
'Ohio' in frame3.columns

True

In [81]:
2003 in frame3.index

False

## 5.2 핵심 기능 

### 5.2.1 재색인

In [122]:
obj = Series([4.5,7.2,-5.3,3.6], index=['d','b','a','c'])

In [123]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [124]:
obj2=obj.reindex(['a','b','c','d','e'])

In [125]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [126]:
obj is obj2

False

In [127]:
obj.reindex(['a','b','c','d','e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [130]:
obj3=Series(['blue','purple','yellow'], index=[0,2,4])

In [131]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [129]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [132]:
obj3.reindex(range(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [133]:
frame=DataFrame(np.arange(9).reshape((3,3)), index=['a','c','d'], columns=['Ohio','Texas','California'])

In [134]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [135]:
frame2=frame.reindex(['a','b','c','d'])

In [92]:
frame2

Ohio  Texas  California
a     0      1           2
b   NaN    NaN         NaN
c     3      4           5
d     6      7           8

In [93]:
states=['Texas','Utah','California']

In [94]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [136]:
frame.reindex(index=['a','b','c','d'], method='ffill', columns=states)

California  Ohio  Oregon  Texas
a           2     0     NaN      1
b           2     0     NaN      1
c           5     3     NaN      4
d           8     6     NaN      7

In [137]:
frame.ix[['a','b','c','d'], states]

California  Ohio  Oregon  Texas
a           2     0     NaN      1
b         NaN   NaN     NaN    NaN
c           5     3     NaN      4
d           8     6     NaN      7

### 5.2.2 하나의 로우 또는 컬럼 삭제하기 

In [99]:
obj=Series(np.arange(5.),index=['a','b','c','d','e'])

In [100]:
new_obj = obj.drop('c')

In [101]:
new_obj

a    0
b    1
d    3
e    4
dtype: float64

In [102]:
obj.drop(['d','c'])

a    0
b    1
e    4
dtype: float64

In [151]:
data=DataFrame(np.arange(16).reshape((4,4)), index=['Ohio','Colorado','Utah','New York'], columns=['one','two','three','four'])

In [152]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [153]:
data.drop('New York')

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11

In [154]:
data.drop(['Colorado','Ohio'], axis=0)

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [155]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [156]:
data.drop(['two','four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

### 5.2.3 색인하기, 선택하기, 거르기 

In [160]:
obj = Series(np.arange(4.),index=['a','b','c','d'])

In [161]:
obj

a    0
b    1
c    2
d    3
dtype: float64

In [162]:
obj['b']

1.0

In [163]:
obj[1]

1.0

In [164]:
obj[2:4]

c    2
d    3
dtype: float64

In [165]:
obj[['b','a','d']]

b    1
a    0
d    3
dtype: float64

In [166]:
obj[[1,3]]

b    1
d    3
dtype: float64

In [167]:
obj[obj < 2]

a    0
b    1
dtype: float64

In [169]:
obj

a    0
b    1
c    2
d    3
dtype: float64

- 레이블과 함께 슬라이싱하면 두 번재 인덱스 값도 포함된다.

In [168]:
obj['b':'c']

b    1
c    2
dtype: float64

In [170]:
obj['b':'c'] = 5

In [171]:
obj

a    0
b    5
c    5
d    3
dtype: float64

In [172]:
data=DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])

In [173]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [183]:
data['two']

Ohio         0
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [184]:
data[['three','one']]

three  one
Ohio          0    0
Colorado      6    0
Utah         10    8
New York     14   12

In [185]:
data[:2]

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7

In [186]:
data[:1]

one  two  three  four
Ohio    0    0      0     0

In [182]:
data.ix['Ohio']

one      0
two      0
three    0
four     0
Name: Ohio, dtype: int64

In [179]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [181]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [190]:
data[data < 5]

one  two  three  four
Ohio        0    0      0     0
Colorado    0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

In [191]:
data[data < 5] = 0

In [192]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [194]:
data.ix[['Colorado','Utah'],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [130]:
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [132]:
data.ix[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [197]:
data.ix[data.three > 5, :3]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

계속....